### ISSUE TITLE
win10 cygwin exit with gnome3

### ISSUE THREAD

**Issue by plutoid** [genzj/pybingwallpaper#41]
Hi，

我再win10上 cygwin/python3跑的，提示gnome3然后就退出了，怎么避免呢？
[2016-01-07 10:14:43,593 - INFO - main] download photo of "摩洛哥，马扎甘葡萄牙城 (© Michele Falzone/AWL/plainpicture)"
[2016-01-07 10:14:43,817 - INFO - main] file saved /home/C5197505/MyBingWallpapers/wallpaper.jpg
Traceback (most recent call last):
  File "src/main.py", line 702, in <module>
    start_daemon()
  File "src/main.py", line 597, in start_daemon
    main(daemon)
  File "src/main.py", line 574, in main
    s = setter.get(run_config.setter)()
  File "/home/C5197505/pybingwallpaper/src/setter.py", line 72, in get
    'unregistered setter {}'.format(name))
NameError: unregistered setter gnome3

BRs,
Hua

**Comment by genzj** [comment]
你先试试加下面这个参数运行能不能成功：

```
--setter=win
```


Tian, Hua <notifications@github.com>于2016年1月7日周四 上午10:25写道：
