### ISSUE TITLE
ubuntu启动报错

### ISSUE THREAD

**Issue by lslvxy** [genzj/pybingwallpaper#43]
loading from http://www.bing.com/HPImageArchive.aspx?format=js&mbl=1&idx=0&n=1&video=1
[2016-03-07 15:34:34,587 - CRITICAL - main] error happened during loading from bing.com.
Traceback (most recent call last):
  File "main.py", line 427, in download_wallpaper
    s.load()
  File "/home/ls/Github/pybingwallpaper/src/bingwallpaper.py", line 222, in load
    rawfile = webutil.loadpage(self.url)
  File "/home/ls/Github/pybingwallpaper/src/webutil.py", line 83, in loadpage
    data = loadurl(url, headers=headers, optional=optional)
  File "/home/ls/Github/pybingwallpaper/src/webutil.py", line 74, in loadurl
    data = con.read(-1)
  File "/usr/lib/python3.5/http/client.py", line 447, in read
    b = bytearray(amt)
ValueError: negative count

**Comment by genzj** [comment]
应该是py35对read参数增加了新的检查，我会在近期修改。谢谢！

**Comment by genzj** [comment]
已经修改在`rev_1_5_dev`流上，如果熟悉git的话，可以做`git fetch && git checkout rev_1_5_dev`切换分支后使用。如果不熟悉git，可以等下个版本发布。
