### ISSUE TITLE
unable install over linux

### ISSUE THREAD

**Issue by efazati** [genzj/pybingwallpaper#50]
Hi, I clone project but i couldn't install your package

at first i get error in dependency

```
$ sudo python setup.py --build
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from cx_Freeze import setup, Executable
ImportError: No module named cx_Freeze
```

but again there is issues

```
$ python setup.py --build
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from main import REV
  File "src/main.py", line 9, in <module>
    import record
  File "src/record.py", line 7, in <module>
    from collections import UserDict
ImportError: cannot import name UserDict
```

What is the problem? why this package there isn't in pip ? also i use pip from git but didn't help at all!

---------------
I found your package is python 3 package 

I use pip3 but not work again
1- install cx_freeze
2- use pip 

```
$ sudo pip3 install git+https://github.com/genzj/pybingwallpaper.git
Downloading/unpacking git+https://github.com/genzj/pybingwallpaper.git
  Cloning https://github.com/genzj/pybingwallpaper.git to /tmp/pip-141u0wi0-build
  Running setup.py (path:/tmp/pip-141u0wi0-build/setup.py) egg_info for package from git+https://github.com/genzj/pybingwallpaper.git
    
Installing collected packages: PyBingWallpaper.exe
  Running setup.py install for PyBingWallpaper.exe
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-141u0wi0-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-5gbihb6e-record/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

   or: -c --help [cmd1 cmd2 ...]

   or: -c --help-commands

   or: -c cmd --help



error: option --single-version-externally-managed not recognized

----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-141u0wi0-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-5gbihb6e-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-141u0wi0-build
Storing debug log for failure in /home/argus/.pip/pip.log
```

also I use python3 setup.py 

```
user@ubuntu:~/projects/pybingwallpaper-master$ sudo python3.4 setup.py build
running build
running build_exe
error: error in setup script: command 'build_exe' has no such option 'compressed'
user@ubuntu:~/projects/pybingwallpaper-master$ sudo python3.4 setup.py install
running install
running build
running build_exe
error: error in setup script: command 'build_exe' has no such option 'compressed'
```

**Comment by genzj** [comment]
Thanks for letting me know. I'll make it pip compatible and easy to build in two or three days.

**Comment by genzj** [comment]
I've registered and uploaded it to PyPi. It would be really nice if you could help me test it before I officially documented the installation procedure and let me know the result.
You can try with (isolate the installation with a virutalenv would be a good idea):

```bash
pip3 install PyBingWallpaper
# then run with
BingWallpaper
```

By `pip3` I mean the pip for Python 3. It may have other name on you OS, just use the proper one.

The source is compatible with Python 2 now but I haven't figure out how to make the PyPi registry works for both. So please test only with Py3.

Thanks again.

**Comment by efazati** [comment]
Yes i tested your application from pip and everything work fine
