### ISSUE TITLE
1.5.4版本下载中国版水印的图报错

### ISSUE THREAD

**Issue by formular2** [genzj/pybingwallpaper#55]
参数如下
[Download]
country = cn
market = 
**keep_file_name = True**
size_mode = highest
collect = **accompany**,hdvideo
image_size = 
offset = 0
redownload = False
output_folder = E:\Pictures\Bing\WallPapers
server = china
customserver = 

按这个配置应该是下载英文版和中文版水印图各一张，以原始文件名保存，下载英文版成功，下载中文版时报错
[2019-03-21 13:15:50,160 - INFO - bingwallpaper.main] download photo of "【今日
春分】  (© Raymond Shi/EyeEm/Getty Images)"
[2019-03-21 13:15:50,385 - INFO - bingwallpaper.main] file saved E:\Pictures\Bin
g\WallPapers\OHR.springequinox_ZH-CN1099430476_1920x1200.jpg
Traceback (most recent call last):
  File "BingWallpaper", line 7, in <module>
  File "pybingwallpaper\main.py", line 802, in main
  File "pybingwallpaper\main.py", line 641, in start
  File "pybingwallpaper\main.py", line 510, in download_wallpaper
  File "pybingwallpaper\main.py", line 527, in collect_assets
  File "pybingwallpaper\main.py", line 544, in save_a_picture
OSError: [Errno 22] Invalid argument: 'E:\\Pictures\\Bing\\WallPapers\\th?id=OHR
.springequinox_ZH-CN1099430476_ZH_1920x1200.jpg'

目测是保存中文版图片的文件名还是带？了。

**Comment by genzj** [comment]
是命名的一个bug，我已经修复了，麻烦升级一下1.5.5版本：

https://github.com/genzj/pybingwallpaper/releases/tag/REV_1_5_5

**Comment by formular2** [comment]
> 是命名的一个bug，我已经修复了，麻烦升级一下1.5.5版本：
> 
> https://github.com/genzj/pybingwallpaper/releases/tag/REV_1_5_5

已验证解决，感谢！
