### ISSUE TITLE
-b -c auto --interval 2这个参数错了吗？

### ISSUE THREAD

**Issue by hrflni** [genzj/pybingwallpaper#56]
是要把 --interval 2 放在 -b 后面吗？

**Comment by hrflni** [comment]
failed to execute script bingwallpaper
出错之后就开不了。

**Comment by genzj** [comment]
参数没问题的，`-b`和`--interval 2`顺序颠倒没关系。

是windows版对吧？报错信息是个对话框弹出的吗？请尝试下从cmd命令行进入安装目录，执行

```
BingWallpaper-cli.exe -b -c auto --interval 2
```

如果在命令行有输出请把输出给我看看。如果还是弹出对话框报错，应该是文件损坏，重装多半能好。

**Comment by hrflni** [comment]
> 
> 
> 参数没问题的，`-b`和`--interval 2`顺序颠倒没关系。
> 
> 是windows版对吧？报错信息是个对话框弹出的吗？请尝试下从cmd命令行进入安装目录，执行
> 
> ```
> BingWallpaper-cli.exe -b -c auto --interval 2
> ```
> 
> 如果在命令行有输出请把输出给我看看。如果还是弹出对话框报错，应该是文件损坏，重装多半能好。

BingWallpaper-cli.exe : 无法将“BingWallpaper-cli.exe”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的
拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ BingWallpaper-cli.exe -b -c auto --interval 2
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (BingWallpaper-cli.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: 找不到命令 BingWallpaper-cli.exe，但它确实存在于当前位置。默认情况下，Windows PowerShell 不会从 当前位置加载命令。如果信任此命令，请改为键入“.\BingWallpaper-cli.exe”。有关详细信息，请参阅 "get-help about_Command_Precedence"。

**Comment by hrflni** [comment]
[2019-04-29 21:14:55,408 - INFO - bingwallpaper.main] running config is:
        background = True
        collect = ['accompany', 'hdvideo']
        config_file = 'e:\\pybingwallpaper\\settings.conf'
        country = 'auto'
        customserver = ''
        database_file = ''
        database_no_image = False
        debug = 0
        foreground = False
        generate_config = False
        image_size = ''
        interval = 2
        keep_file_name = True
        market = ''
        offset = 0
        output_folder = 'E:\\MyBingWallpapers'
        proxy_password = ''
        proxy_port = '80'
        proxy_server = ''
        proxy_username = ''
        redownload = False
        server = 'global'
        setter = 'win'
        setter_args = []
        size_mode = 'highest'
[2019-04-29 21:14:55,408 - INFO - bingwallpaper.main] daemon <sched.scheduler object at 0x034AED10> triggers an update
[2019-04-29 21:14:55,408 - INFO - bingwallpaper.main] running config is:
        background = True
        collect = ['accompany', 'hdvideo']
        config_file = 'e:\\pybingwallpaper\\settings.conf'
        country = 'auto'
        customserver = ''
        database_file = ''
        database_no_image = False
        debug = 0
        foreground = False
        generate_config = False
        image_size = ''
        interval = 2
        keep_file_name = True
        market = ''
        offset = 0
        output_folder = 'E:\\MyBingWallpapers'
        proxy_password = ''
        proxy_port = '80'
        proxy_server = ''
        proxy_username = ''
        redownload = False
        server = 'global'
        setter = 'win'
        setter_args = []
        size_mode = 'highest'
[2019-04-29 21:14:55,439 - INFO - bingwallpaper.bingwallpaper] loading from http://www.bing.com/HPImageArchive.aspx?format=js&mbl=1&idx=0&n=1&video=1
[2019-04-29 21:14:55,769 - INFO - bingwallpaper.bingwallpaper] 788 bytes loaded
[2019-04-29 21:14:55,769 - WARNING - bingwallpaper.bingwallpaper] links to be downloaded: [(('http://www.bing.com/th?id=OHR.BabySloth_ZH-CN8329403615_1920x1200.jpg', 'http://www.bing.com/th?id=OHR.BabySloth_ZH-CN8329403615_ZH_1920x1200.jpg'), {'copyright': '棕色褐喉树懒幼崽与妈妈，哥斯达黎加树懒保护区 (© Suzi Eszterhas/Minden Pictures)', 'startdate': '20190428', 'copyrightlink': 'http://www.bing.com/search?q=%E6%A3%95%E8%89%B2%E8%A4%90%E5%96%89%E6%A0%91%E6%87%92&form=hpcapt&mkt=zh-cn', 'hsh': 'bf21ce5e063d35e9e4a7afdd9cf2a7ae', 'market': 'zh-CN'})]
[2019-04-29 21:14:55,769 - INFO - bingwallpaper.main] download photo of "棕色褐喉树懒幼崽与妈妈，哥斯达黎加树懒保护区 (© Suzi Eszterhas/Minden Pictures)"
[2019-04-29 21:14:56,279 - INFO - bingwallpaper.main] file saved E:\MyBingWallpapers\OHR.BabySloth_ZH-CN8329403615_1920x1200.jpg
Traceback (most recent call last):
  File "BingWallpaper", line 7, in <module>
  File "pybingwallpaper\main.py", line 800, in main
  File "pybingwallpaper\main.py", line 683, in start_daemon
  File "pybingwallpaper\main.py", line 641, in start
  File "pybingwallpaper\main.py", line 510, in download_wallpaper
  File "pybingwallpaper\main.py", line 527, in collect_assets
  File "pybingwallpaper\main.py", line 544, in save_a_picture
OSError: [Errno 22] Invalid argument: 'E:\\MyBingWallpapers\\th?id=OHR.BabySloth_ZH-CN8329403615_ZH_1920x1200.jpg'
[5828] Failed to execute script BingWallpaper



这个是CMD下的。

**Comment by genzj** [comment]
是命名的一个bug，我已经修复了，麻烦升级一下1.5.5版本：

https://github.com/genzj/pybingwallpaper/releases/tag/REV_1_5_5

**Comment by hrflni** [comment]
> 
> 
> 是命名的一个bug，我已经修复了，麻烦升级一下1.5.5版本：
> 
> https://github.com/genzj/pybingwallpaper/releases/tag/REV_1_5_5

谢谢！
